### ISSUE TITLE
Want a little adjustment make generated file compatible with scenario_runner CARLA

### ISSUE THREAD

**Issue by Vela-zz** [pyoscx/pyoscx#12]
Thanks for your group write this project and let us can make an openScenario File for CARLA scenario runner quickly
But the generated file is still some incompatible with scenario runner format,

The format validation used in scenario runner is:

[OpenSCENARIO.xsd](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/openscenario/OpenSCENARIO.xsd)

for Example:
1.
`env = psx.Environment(
            timeofday=psx.TimeOfDay("false",2020,12,25,17,30,1),
            weather=wea,
            roadcondition=psx.RoadCondition(friction_scale_factor=1.0)
        )`

will generate a slice of XML like 

						<Environment>
							<TimeOfDay animation="false" dateTime="2020-12-25T17:30:1"/>
							<Weather cloudState="free">
								<Sun azimuth="0" elevation="1.31" intensity="0.85"/>
								<Fog visualRange="100000"/>
								<Precipitation intensity="0.0" precipitationType="dry"/>
							</Weather>
							<RoadCondition frictionScaleFactor="1.0"/>
						</Environment>

that the timestamp tag of dateTime is invalid "2020-12-25T17:30:1" -> "2020-12-25T17:30:01"

2.
In `<Init>` part, scenario_runner requires`<GlobalAction>` at 1st place,
like 

                                                              <Init>
                                                                      <GlobalAction\>
                                                                      <PrivateAction\>

 but pyoscx will put `<PrivateAction>` at the 1st place, 
like:

                                                           <Init>
                                                                 <PrivateAction\>
                                                                 <GlobalAction\>

I just ask if it can be adjusted by your team, or I would adjust this part by myself
Thanks for you all..

**Comment by MandolinMicke** [comment]
Hi
The datetime should be an easy fix, if you want to fix it do (I will not have time in a week or so). 

Sadly I don't understand what you mean in your second example? Can you clearify?

//Micke

**Comment by Vela-zz** [comment]
> Hi
> The datetime should be an easy fix, if you want to fix it do (I will not have time in a week or so).
> 
> Sadly I don't understand what you mean in your second example? Can you clearify?
> 
> //Micke
Sorry, I've updated 2nd Question, it had been hided because the wrong way I wrote xml tag in question

**Comment by MandolinMicke** [comment]
Hmm, for the second one I'll check the documentation to see if there is a formal way to handle this.

**Comment by mander76** [comment]
I have fixed both issues, in the newest push.

The order is however not defined specifically as a "requirement" in openscenario, but it shouldn't matter.
