### ISSUE TITLE
RouteStrategy is String

### ISSUE THREAD

**Issue by TKeutgens** [pyoscx/pyoscx#2]
Hello thank you very much for providing the library. It is exactly what I was looking for. 

If found an issue. Under utils:

`return {'routeStrategy':self.routestrategy.name}`

routestrategy is a string and thus the .name reference does not work.

**Comment by MandolinMicke** [comment]
I'll look into it!

**Comment by MandolinMicke** [comment]
RouteStrategy should be an Enum (see enumerations.py), hence the .name you are referring to. So it is as it should.

Please confirm and I'll close this issue.

class RouteStrategy(Enum):
    """ Enum for RouteStrategy
    """
    fastest = auto()
    shortest = auto()
    leastIntersections = auto()
    random = auto()

**Comment by MandolinMicke** [comment]
Closing issue
