### ISSUE TITLE
Lowercase mistake in enumerations

### ISSUE THREAD

**Issue by haolijunATdl** [pyoscx/pyoscx#3]
Hello, Thanks for your providing of this library.
There's a lowercase mistake in the enumerations.
"rising**o**rFalling" in ConditionEdge should be "rising**O**rFalling" acorrding to OpenSCENARIO's definition.
And it causes an error when create scenarios.

**Comment by eknabevcc** [comment]
Hopefully fixed now with commit [9ec5130](https://github.com/esmini/esmini/commit/9ec5130d826df9a29d2a41ee9599aae82d2df3f7). Please try.

**Comment by MandolinMicke** [comment]
Thanks for the find! 

And thanks for the fix Emil!
