### ISSUE TITLE
EnvironmentAction

### ISSUE THREAD

**Issue by TKeutgens** [pyoscx/pyoscx#4]
First of all, thanks for adding the environment action to the library. This ist a very useful feature for using the OpenScenario files in a simulator.  

I've tried to use the environment action in an example by adding the following lines of code:
`    # initialize variables needed for scenario
    init = pyoscx.Init()
    #Add Environment Action to Initialization
    envaction = createEnvironmentAction()
    init.add_init_action("envaction",envaction)`

The result looks like this: 
![grafik](https://user-images.githubusercontent.com/61495604/96586366-2f927100-12e1-11eb-9e3e-51626db74090.png)

It seems like the add_init_action only allows for the addition of private actions. Could you perhaps share an example on how to propperly add the environment action to the initialization. 

Thanks!

**Comment by pyoscx** [comment]
Hi TKeutgens

This is actually a bug, I'll try to fix it during the day.

**Comment by pyoscx** [comment]
Hi again, 

Thanks for finding that bug :)

In change commit 5ad2663621075ad94a0f5206c0b49d2ad251454b, 
the posibility to add a global action to the init is added 

A global action can now be added like this
init = pyoscx.Init()
init.add_global_action(pyoscx.AddEntityAction('Ego',pyoscx.WorldPosition()))

**Comment by pyoscx** [comment]
closing
